export const resetForm = {
  productName: "",
  productCategory: "",
  productPrice: "",
  productQuantity: "",
  productDescription: "",
  productSpecifications: "",
  productExpired: "",
  image: "",
  createdAt: "",
  productType: "",
  productCompany: "",
  productNumber: "",
  productCapsule: "",
  productCountry: "",
  productAge: "",
  productProcess: "",
};
