export const resetForm = {
  productName: "",
  productCategory: "",
  productPrice: 0,
  productQuantity: 0,
  productDescription: "",
  productSpecifications: "",
  productExpired: "",
  image: "",
  createdAt: "",
  productType: "",
  productCompany: "",
  productNumber: 0,
  productCapsule: "",
  productCountry: "",
  productAge: 0,
  productProcess: "",
  id: "",
};
