export const faLocalization = {
  loginOrRegister: "ثبت نام | ورود",
  search: "محصول مورد نظر خود را جستجو کنید...",
  cart: "سبد خرید",
  edit: "ویرایش",
  delete: "حذف",
  deleting: "در حال حذف...",
  loading: "درحال بارگزاری...",
  errorInImageUpload: "آپلود تصویر با خطا مواجه شد",
  sending: "در حال ارسال...",
  update: "بروزرسانی",
  prev: "قبلی",
  next: "بعدی",
  page: "صفحه",
  from: "از",
  year: "سال به بالا",
  errorInFetchingCategories: "خطا در دریافت دسته بندی",
  errorInAddingCategories: "خطا در اضافه کردن دسته بندی",
  add: "افزودن",
  adding: "در حال افزودن...",
  rial: "ریال",
  noData: "اطلاعاتی برای نمایش وجود ندارد.",
  noProductFound: "محصولی برای نمایش وجود ندارد.",
  saving: "در حال ذخیره...",
  save: "ذخیره",
  show: "نمایش",
  management: "مدیریت",
  blogs: "مجله داروفارم",
  userProfile: "مشخصات کاربری",
  orders: "سفارش‌ها",
  favorites: "لیست علاقه‌مندی‌ها",
  logout: "خروج از حساب کاربری",
  first: "اولین صفحه",
  end: "آخرین صفحه",
  welCome: "خوش آمدید",
  close: "بستن",
  operation: "عملیات",
  noPageFound: "صفحه ای یافت نشد",
  logo: "داروفارم",
  why: "چرا",
  chooseThis: "را انتخاب کنیم؟",
  articles: "خواندنی های",
  readMore: " بیشتر بخوانید ",
  noDrugInCategory: "هیچ دارویی برای این دسته‌بندی وجود ندارد",
  products: "محصولات",
  just: "فقط",
  isAvailable: "عدد در انبار موجود است.",
};

export const sweetAlert = {
  areYouSure: "آیا مطمئنی؟",
  irrevocable: "این عملیات قابل بازگشت نیست!",
  yesDelete: "بله، حذف کن!",
  cancel: "لغو",
  ok: "تایید",
  delete: "حذف شد.",
  deleteCategory: "دسته‌بندی حذف شد.",
  deleteProduct: "محصول موردنظر حذف شد.",
  edit: "ویرایش شد!",
  addSubCategory: "زیردسته اضافه شد.",
  editSubCategory: "زیردسته ویرایش شد.",
  successfullyEdited: "با موفقیت ویرایش شد",
  seccessfullyAdded: "با موفقیت افزوده شد",
  successfullyDeleted: "با موفقیت حذف شد.",
  okay: "باشه",
  errorInSubmit: "خطا در ثبت اطلاعات",
  tryAgain: "لطفاً مجدداً تلاش کنید.",
  errorInReceiveData: "خطا در دریافت اطلاعات",
  errorInSendingData: "خطا در ارسال اطلاعات",
  error: "خطا",
  del: "حذف",
  errorInDeleteData: "خطا در حذف",
  successful: "محصول با موفقیت ادد شد.",
  successfulEdit: "محصول با موفقیت ویرایش شد.",
  noAdminFound:
    "اطلاعات ادمین موردنظر ثبت نیست. لطفا از دکمه افزودن اطلاعات ادمین استفاده کنید.",
  adminError: "شما به اطلاعات این قسمت دسترسی ندارید. ",
};

export const adminCategories = {
  categoriesList: "لیست دسته بندی ها",
  addCategory: "افزودن دسته بندی",
  categoryName: "نام دسته بندی",
  cancel: "لغو",
  confirm: "تایید",
  loading: "در حال بارگذاری...",
  save: "ذخیره",
  edit: "ویرایش",
  delete: "حذف",
  add: "افزودن",
  repetitive: "دسته‌ای با این عنوان قبلاً اضافه شده است.",
};

export const loginLocalization = {
  Login: " ورود",
  DontHaveAccount: "آیا قبلا حساب کاربری داشته اید؟",
  SignupHere: " ثبت نام کنید ",
  Email: " ایمیل ",
  Password: " رمز ورود ",
  RememberMe: " مرا بخاطر بسپار ",
  ForgotPassword: " فراموشی رمز عبور ",
  EnterEmail: " ایمیل خود را وارد کنید ",
  EnterPassword: " رمز خود را وارد کنید ",
  loginError: "رمز ورود یا ایمیل اشتباه است.",
  toastError: "ورود موفقیت‌آمیز نبود.",
  successLogin: "ورود با موفقیت انجام شد!",
  allFieldsRequired: "همه فیلدها باید پر باشند.",
  logoutSuccessfully: "شما با موفقیت از حساب خود خارج شدید.",
  wannaLogout: "خروج از حساب کاربری",
  yes: "بله",
  no: "خیر",
};

export const signUpLocalization = {
  Password: " رمز ورود ",
  EnterPassword: " رمز خود را وارد کنید  ",
  signUpDescription:
    " با ثبت نام، با دریافت به روز رسانی ها و پیشنهادات ویژه موافقت می کنید. ",
  Signup: " ثبت نام ",
  AlreadyHaveAccount: " آیا قبلا حساب کاربری داشتید؟ ",
  Login: "ورود",
  Name: " نام ",
  EnterName: " نام خود را وارد کنید ",
  Email: " ایمیل ",
  EnterEmail: " ایمیل خود را وارد کنید  ",
  tryAgain: "این ایمیل قبلا ثبت نام کرده است.",
  confirm: "تایید",
  confirming: "در حال تایید...",
};
export const validateLocalization = {
  usernameRegex: "یوزرنیم شامل اعداد و حروف است. (3-20 کاراکتر)",
  emailRegex: "فرمت ایمیل نامعتبر است.",
  passwordRegex: "پسورد شامل اعداد، حروف بزرگ و حروف کوچک باشد. (8-11 کاراکتر)",
};

export const adminHeaderLocalization = {
  dearAdmin: "ادمین جدید",
  hi: "سلام",
  dear: "عزیز!",
};

export const asideBarLocalization = {
  storeName: "داروفارم",
  exit: "خروج از حساب کاربری",
  pleaseWait: "لطفا صبر کنید...",
};

export const dashboardLocalization = {
  managementDashboard: "داشبورد مدیریت",
  users: "کاربران",
  orders: "سفارشات",
  totalIncome: "درآمد کل",
  rial: "ریال",
  categoriesNumber: "تعداد محصولات در هر دسته‌بندی",
  categoriesOrder: " محصولات سفارش داده شده به تفکیک دسته‌بندی",
};

export const deliveryMethodsLocalization = {
  deliveryMethodsManagment: "مدیریت روش‌های ارسال",
  addNewMethod: "افزودن روش جدید",
  methodName: "نام روش ارسالی",
  typeHere: "اینجا بنویسید...",
  free: "ارسال رایگان از مبلغ",
  minCost: "حداقل هزینه ارسال",
  maxWeight: "حداکثر وزن قابل ارسال (کیلوگرم)",
  editing: "در حال ویرایش...",
  adding: "در حال افزودن...",
  edit: "ویرایش روش ارسال",
  name: "نام",
  operation: "عملیات",
  kilo: "کیلوگرم",
  rial: "ریال",
  addNamePlease: "لطفاً نام روش ارسالی را وارد کنید.",
  close: "بستن",
};

export const blogLocalization = {
  addImage: "لطفاً تصویر را بارگذاری کنید",
  addPost: "افزودن پست جدید",
  chooseImage: "انتخاب تصویر پست",
  notChoosen: "فایلی انتخاب نشده است",
  title: "عنوان",
  abstract: "خلاصه",
  content: "محتوا",
  savePost: "ذخیره پست",
  deleteError: "مشکلی در حذف پست پیش آمده است.",
  editError: "مشکلی در ویرایش پست پیش آمده است.",
  loading: "در حال دریافت پست ها...",
  noPostToShow: "هیچ پستی وجود ندارد.",
  blogs: "خواندنی ها",
};

export const productsLocalization = {
  errorInReceiveData: "دریافت محصولات با خطا مواجه شد.",
  errorInUploadImage: "آپلود تصویر با خطا مواجه شد",
  addImagePlease: "لطفاً تصویر را بارگذاری کنید",
  repetitive: "محصول با این نام قبلاً موجود است",
  errorInSendingData: "مشکلی در ارسال اطلاعات پیش آمده است",
  addProduct: "افزودن محصول",
  allCategories: "همه دسته بندی ها",
  chooseCategories: "انتخاب دسته بندی ها",
  all: "همه محصولات",
  unavailable: "ناموجود",
  low: "کمتر از 10",
  enough: "10 یا بیشتر",
  newest: "جدیدترین",
  oldest: "قدیمی‌ترین",
  az: "مرتب A-Z",
  za: "مرتب Z-A",
  id: "کد محصول",
  image: "تصویر",
  name: "نام",
  category: "دسته",
  price: "قیمت",
  available: "موجودی",
  expireDate: "تاریخ انقضا",
  operation: "عملیات",
  notFound: "محصولی یافت نشد.",
  undefiend: "نامشخص",
  delete: "حذف محصول",
  edit: "ویرایش محصول",
  detail: "جزئیات محصول",
  description: "توضیحات",
  specification: "ویژگی‌ها",
  close: "بستن",
  productName: "نام محصول",
  productCategory: "دسته بندی محصول",
  productExpired: "تاریخ انقضای محصول",
  choosenFile: "فایل انتخاب شده",
  errorInEditingProduct: "خطا در ویرایش محصول",
  loading: "در حال بارگزاری...",
  canNotBeNegative: "تعداد محصول نمی تواند منفی باشد",
  copyId: "شناسه محصول کپی شد",
  notCopyId: "شناسه محصول کپی نشد",
  discount: "تخفیف",
  information: "اطلاعات محصول",
  addToCart: "افزودن به سبد خرید",
  filters: "فیلترها",
  justAvailable: "فقط کالاهای موجود",
  justOffer: "فقط کالاهای تخفیف‌دار",
  categories: "دسته‌بندی‌ها",
  sortBy: "مرتب سازی براساس:",
  removeFav: "از علاقه‌مندی‌ها حذف شد",
  addFav: "به علاقه‌مندی‌ها اضافه شد",
  loginError: "ابتدا عضو سایت شوید.",
  productType: "نوع محصول",
  company: "شرکت سازنده",
  number: "تعداد محصول",
  capsule: "نوع محفظه",
  country: "کشور سازنده",
  process: "گروه",
  age: "سن مصرف",
};

export const newestProduct = {
  newProduct: "محصولات جدید",
  addNewProduct: "افزودن محصول جدید",
  addID: "افزودن آیدی محصول",
  addProductID: "آیدی محصول را وارد کنید",
  duplicate: "این محصول قبلاً اضافه شده است.",
};

export const bestSeller = {
  bestSellerProduct: "محصولات پرفروش",
};

export const bannerLocalization = {
  addBanner: "افزودن بنر",
  title: "عنوان",
  description: "توضیحات",
  link: "لینک هدایت‌شونده (اختیاری)",
  order: "ترتیب",
  isActive: "فعال باشد",
  mainImage: "تصویر اصلی بنر:",
  bgImage: "تصویر پس‌زمینه:",
  saveBanner: "ثبت بنر",
  errorInEditBanner: "ویرایش بنر با مشکل مواجه شد.",
  existOrder: "شماره ترتیب قبلاً استفاده شده است. لطفاً عدد دیگری وارد کنید.",
};

export const offerProducts = {
  offProducts: "محصولات تخفیف دار",
  discountPercent: "درصد تخفیف",
  discountZeroError: "درصد تخفیف باید بیشتر از صفر باشد",
};

export const ordersLocalization = {
  ordersManagement: "مدیریت سفارش ها",
  all: "همه",
  delivered: "تحویل داده شده",
  inDelivery: "در حال ارسال",
  placeholder: "شناسه سفارش را وارد کنید",
  id: "شناسه سفارش",
  customer: "مشتری",
  createdAt: "زمان ثبت",
  totalPrice: "مبلغ کل",
  status: "وضعیت",
  detail: "جزئیات",
  ordersDetail: "جزئیات سفارش ",
  deliveryTime: "زمان تحویل",
  ordersProducts: "محصولات سفارش",
  item: "عدد",
  sum: "مجموع",
  saveChanges: "ذخیره تغییرات",
  deleteOrder: "حذف سفارش",
};

export const adminLocalization = {
  adminsList: "لیست ادمین ها",
  username: "نام کاربری",
  email: "ایمیل",
  age: "تاریخ تولد",
  education: "تحصیلات",
  phone: "شماره تماس",
  fullName: "نام و نام خانوادگی",
  operation: "عملیات",
  showAdmin: "مشاهده اطلاعات ادمین",
  editAdmin: "ویرایش اطلاعات ادمین",
  saveChanges: "ذخیره تغییرات",
  close: "بستن",
  firstName: "نام",
  lastName: "نام خانوادگی",
  address: "آدرس",
};

export const pageLocalization = {
  aboutUs: "درباره ما",
  contactUs: "تماس با ما",
  contactUsEdit: "ویرایش تماس با ما",
  title: "عنوان",
  address: "آدرس",
  email: "ایمیل",
  phone: "شماره تماس",
  managerConnection: "ارتباط با مدیریت",
  resumeEmail: "ارسال رزومه",
  privacy: "قوانین و مقررات",
  guide: "راهنمای خرید",
  description:
    "کارشناسان ما در اسرع وقت به پیام شما رسیدگی نموده و پاسخ خواهند داد.",
  textarea: "متن پیام خود را در این بخش یادداشت فرمایید.",
  send: "ثبت",
  required: "فیلد مربوط به نام و شماره تماس نباید خالی باشد.",
  phoneRegex: "شماره موبایل باید با ۰۹ شروع شود و دقیقاً ۱۱ رقم باشد",
  successfullMessage: "پیام شما با موفقیت ارسال شد!",
};

export const UsersLocalization = {
  usersList: "لیست کاربران",
  usersDetail: "اطلاعات کاربر",
  loginDate: "تاریخ عضویت",
  add: "افزودن اطلاعات ادمین",
  adminDetail: "اطلاعات ادمین",
  choose: "انتخاب کنید",
  detail: "جزئیات",
  search: "یوزرنیم کاربر مورد نظر خود را وارد کنید",
  noUsersFound: "هیچ کاربری یافت نشد.",
};

export const FooterLocalization = {
  description:
    "ما در داروخانه آنلاین تلاش می‌کنیم تا با ارائه خدمات سریع و امن، داروها و مکمل‌های موردنیاز شما را در کمترین زمان به دستتان برسانیم.",
  withDaroopharm: " با داروفارم ",
  customerServices: " خدمات مشتریان",
  profile: " پروفایل کاربری ",
  login: " ورود کاربران ",
  signUp: " ثبت نام ",
  memberShip: "عضویت در خبرنامه ",
  sendEmailForNews:
    "برای دریافت تخفیف‌ها و اطلاع از محصولات جدید، ایمیل خود را وارد کنید.",
  withUs: "همراه ما باشید!",
  copyRight:
    "برای استفاده از مطالب داروفارم، داشتن «هدف غیرتجاری» و ذکر «منبع» کافیست.",
  successEmail: "ایمیل شما با موفقیت ثبت شد!",
  errorInEmail: "خطا در ثبت ایمیل",
  emailPlaceholder: "ایمیل شما",
  memberShipButton: "عضویت",
};

export const cartLocalization = {
  errorInRecieve: "خطا در دریافت اطلاعات",
  errorInAdd: "خطا در افزودن محصول",
  errorInDelete: "خطا در حذف محصول",
  errorInEdit: "خطا در بروزرسانی محصول",
  notEnough: "موجودی کافی نیست",
  errorInIncrease: "خطا در افزایش تعداد محصول",
  errorInDecrease: "خطا در کاهش تعداد محصول",
  emptyCart: "سبد خرید شما خالی است",
  notAddedYet: "محصولی به سبد خرید اضافه نکرده‌اید.",
  cart: "سبد خرید",
  pricePerProduct: "قیمت واحد",
  orderDetail: "جزئیات سفارش",
  totalPrice: "قیمت کل",
  benefit: "سود شما از خرید:",
  payableAmount: "مبلغ قابل پرداخت:",
  continue: "ادامه فرآیند خرید",
  addedSuccessfully: "محصول به سبد خرید اضافه شد",
  addToCart: "افزودن به سبد خرید",
  loginError: "ابتدا وارد حساب کاربری خود شوید.",
};

export const favoriteLocalization = {
  noProduct: "هیچ محصولی در لیست علاقه‌مندی‌ها نیست.",
  favPage: "صفحه علاقه مندی ها",
  seeProduct: "مشاهده محصول",
  loginError: "شما هنوز عضو سایت نشده اید.",
};

export const logoutLocalization = {
  areYouSure: "آیا مطمئنی می‌خواهی خارج شوی؟",
  yesExit: "بله، خارج شو",
};

export const checkOutLocalization = {
  applyDiscount: "کد تخفیف اعمال شد",
  invalidDiscount: "کد تخفیف معتبر نیست",
  allRequired: "تمام اطلاعات کاربر باید وارد شود",
  chooseDelivery: "لطفا روش ارسال را انتخاب کنید",
  userInformation: "اطلاعات کاربر",
  name: "نام محصول",
  pricePerItem: "قیمت واحد",
  count: "تعداد",
  discountPercent: "درصد تخفیف",
  finalPrice: "قیمت نهایی",
  payablePrice: "قیمت پرداختی",
  discountCode: "کد تخفیف",
  deliveryMethod: "روش ارسال",
  apply: "اعمال تخفیف",
  delete: "حذف تخفیف",
  discountRemoved: "کد تخفیف حذف شد",
  time: "زمان ارسال",
  deliveryCost: "هزینه ارسال",
  freeDelivery: "ارسال رایگان",
  continue: "تایید و ادامه به پرداخت",
  minOrderAmount: "حداقل مبلغ سفارشی برای اعمال تخفیف:",
  selectTime: "لطفا زمان ارسال را انتخاب کنید",
  transferingToOrders: "در حال انتقال به صفحه پرداخت...",
  chooseAddress: "آدرس را انتخاب کنید:",
  addAddress: "(برای افزودن آدرس جدید به بخش پروفایل کاربری مراجعه کتید.)",
  chooseDate: "تاریخ را انتخاب کنید",
  cartValidation: "شماره کارت باید دقیقاً ۱۶ رقم باشد.",
  cvvValidation: "CVV2 باید حداقل ۳ رقم باشد.",
  onlinePayment: "پرداخت اینترنتی",
  fullName: "نام و نام خانوادگی دارنده کارت",
  nameHolder: "نام - نام خانوادگی",
  cartNumber: "شماره کارت",
  dateHolder: "ماه / سال",
  secondPass: "رمز دوم (رمز پویا)",
  cvvPass: "رمز cvv2",
  payment: "پرداخت",
  cancel: "انصراف",
  p1: "نام پذیرنده: داروخانه آنلاین داروفارم",
  p2: "شماره ترمینال: 123456789",
  p3: "شماره پذیرنده: 987654321",
  webAddress: "آدرس وبسایت:",
  emptyCart: "سبد خرید شما خالی است.",
};

export const discountLocalization = {
  discountManage: "مدیریت تخفیف‌ها",
  name: "نام تخفیف",
  discount: "مقدار تخفیف",
  edit: "ویرایش تخفیف",
  add: "افزودن تخفیف",
  num: "ردیف",
  operation: "عملیات",
  minOrder: "حداقل خرید",
  required: "لطفا همه فیلدها را پر کنید",
};

export const profileLocalization = {
  created: "پروفایل با موفقیت ایجاد شد!",
  edited: "پروفایل با موفقیت ویرایش شد!",
  deleted: "پروفایل حذف شد.",
  profile: "پروفایل کاربری",
  choose: "انتخاب کنید",
  underDiploma: "زیر دیپلم",
  diploma: "دیپلم",
  associate: "کاردانی",
  bachelor: "کارشناسی",
  master: "کارشناسی ارشد",
  doctora: "دکترا",
  male: "مرد",
  female: "زن",
  gender: "جنسیت",
  addAddress: "+ افزودن آدرس جدید",
  addresses: "آدرس ها",
};
